Adding support for multiple languages
proffapt/code-runner pull request #11
Opened 2022-12-06 06:12 UTC by YoganshSharma

#8 Adding support for perl, lua, ruby and haskell.

2022-12-07 11:30 UTC, proffapt reviewed
Are there no more options available for these langs?
Like compiled binary? debugger? Have you researched?

2022-12-08 17:01 UTC, proffapt commented on run
> +	"--no-persistent" | "np")
no need for it, the code is written keeping this as a default setting in mind

2022-12-08 17:02 UTC, proffapt reviewed
remove the `--no-persistent` flag the program is non-persistent by default

2022-12-08 17:50 UTC, YoganshSharma commented on run
> +	"--no-persistent" | "np")
The code is always persistent in compile mode.
Line 201 is unreachable.

2022-12-08 18:42 UTC, proffapt commented on run
> +	"--no-persistent" | "np")
aa, that's obvious code has to be persistent in compile mode

Persistence means to keep the compiled binary - you are compiling and you want to delete the binary - how does it make sense?

2022-12-09 06:35 UTC, proffapt commented
https://github.com/proffapt/code-runner/pull/11#discussion_r1043701223

@YoganshSharma as said compilation is designed to be persistent; no sense in making it non-persistent - like you compile and then delete what's the logic..

2022-12-09 06:42 UTC, proffapt commented on run
> +        else
fix the orientation here.

2022-12-09 18:04 UTC, proffapt requested changes
I have suggested some changes - let's see your views - if you find them ok - implement them directly from here.

2022-12-09 18:04 UTC, proffapt commented on run
> +		elif [[ $COMPILE == true ]]; then
```suggestion
		if [[ $DEBUG == true ]]; then
			ghci "$FILE"
		fi
		if [[ $COMPILE == true ]]; then
```
Will enable user to use `debug` and `compile` at the same time - idk why but other langs support it for some reason (from the code) so just to maintain the uniformity

2022-12-09 18:04 UTC, proffapt commented on run
> +		fi
```suggestion
```

Not needed here, because for every option there is a different tool - debug, compile and running - thus there will never be binary file when you run it or debug it; there will be an executable only when you compile - and the logistics of compile is persistent by design so you don't want to delete the binaries you just compiled.

If you didn't understand this part - just remind yourself that in other code files like .c or .cpp you have to compile first and then run - which is not the case here.

2022-12-09 18:04 UTC, proffapt commented on run
> +		echo "    ${yellow}>>${white} Haskell"
```suggestion
		echo "    ${yellow}>>${white} Haskell    ${cyan}[${white}with ${green}debug${white} support${cyan}]"
```

2022-12-09 18:04 UTC, proffapt commented on run
> +		fi
Not much of a difference logic wise but maintains uniformity throughout the code - Nice

2022-12-10 07:03 UTC, YoganshSharma reviewed
I have reviewed the changes. It is ready to merge.

2022-12-10 08:00 UTC, proffapt commented
LGTM.

2022-12-10 08:01 UTC, merged